#passing variables to functions for each file?
# can this all read from 1 file? or break up the files?

#s3 files, make file is not in prod

load_data:
 ingest:
 	source_data_url: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
	sed_start_index: 21
	sed_end_index: 50p
	name: clouds.data
	path: ./data

clean:
	save_location: 'data/clean'
	output_file_name: 'train_cleaned.csv'

save_location: 'data/raw'

delete_columns:
- 'ID'
- 'usd_pledged_real'
- 'usd pledged'
- 'launched'
- 'deadline'
- 'name'
- 'backers'
- 'pledged'
			
train_model:	
	start: 
		seed: 42
		split: 0.1  
		params: 
			n_estimators: 150
			max_depth: 3
			learning_rate: 0.2
			min_samples_leaf: 1
			random_state: 3 


	path: ./eval
	file_name: 'evaluation.txt'
	save_location: './models/'
	f_name: 'GradientBoosting.pkl'
